### PR TITLE
chore: introduce common CI, README, etc.

### LINKED ISSUE #25: [Enhancement]: Minetest should no longer ship with Minetest Game
### What changes would you like?

Minetest is a game creation platform with many different games available. From 5.8.0, we no longer recommend shipping with Minetest Game so that the player can chose which game they want to play.

Without MTG, the user is directed to download a game from [ContentDB](https://content.minetest.net) if they wish to play singleplayer. They can continue to play multiplayer without downloading a game (as code is all server-side)

### Any extra information?

For more information, see: https://blog.minetest.net/2023/12/04/5.8.0-released/#minetest-no-longer-ships-with-a-default-game

### LINKED ISSUE #26: [Bug]: Audio not working for 5.8.0
### What happened?

Audio is not working. Error message:

```
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
2024-01-18 18:17:37: ERROR[Main]: Audio: Global Initialization: Failed to open device
```

### What should have happened?

Minetest should find the audio device and use it.

### Output of `snap info $snap_name`

```shell
name:      minetest
summary:   Open source voxel game engine
publisher: Snapcrafters✪
store-url: https://snapcraft.io/minetest
contact:   https://github.com/snapcrafters/minetest/issues
license:   LGPL-2.1-or-later
description: |
  Minetest is a minecraft-inspired game written from scratch and licensed under the LGPL (version
  2.1 or later). It supports both survival and creative modes along with multiplayer support,
  dynamic lighting, and an "infinite" map generator.
  
  **Authors**
  
  This snap package is maintained by the Snapcrafters community. It is not necessarily endorsed or
  officially supported by the developers of the application itself.
commands:
  - minetest
snap-id:      DtXxirDGfOc8LeUJVENXGTir4Oq0F7Ts
tracking:     latest/stable
refresh-date: today at 18:17 JST
channels:
  latest/stable:    5.8.0 2023-12-05 (1882) 66MB -
  latest/candidate: ↑                            
  latest/beta:      5.8.0 2023-12-05 (1882) 66MB -
  latest/edge:      5.8.0 2024-01-12 (1899) 66MB -
installed:          5.8.0            (1882) 66MB -
```

### Output of `snap connections $snap_name`

```shell
Interface        Plug                      Slot             Notes
desktop          minetest:desktop          :desktop         -
desktop-legacy   minetest:desktop-legacy   :desktop-legacy  -
home             minetest:home             :home            -
network          minetest:network          :network         -
network-bind     minetest:network-bind     :network-bind    -
opengl           minetest:opengl           :opengl          -
pulseaudio       minetest:pulseaudio       :pulseaudio      -
removable-media  minetest:removable-media  -                -
x11              minetest:x11              :x11             -
```

### Output of `snap version`

```shell
snap    2.60.4+23.10.1
snapd   2.60.4+23.10.1
series  16
ubuntu  23.10
kernel  6.5.0-14-generic
```

### Relevant log output

_No response_

### Teminal output of app

```shell
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
2024-01-18 18:17:37: ERROR[Main]: Audio: Global Initialization: Failed to open device
```

### PR DESCRIPTION
**Pull request by jnsgruk**
2024-ify this snap with the most recent patterns

- Introduce common README template
- Use shared CI
- Give the snapcraft.yaml some ascending-order love
- Adds arm64 support
- Adds `audio-playback` which should fix #26 
- Removes `minetestgame` part as per #25

### CODE REVIEW

**Comment by popey** [comment]
Builds but fails to launch here. Looks like missing ALSA and Wayland support?

```bash
alan@nuc:~/Source/jnsgruk/minetest$ snap run minetest
2024-03-14 09:37:25: WARNING[Main]: system-wide share not found at "/usr/share/minetest"
2024-03-14 09:37:25: WARNING[Main]: system-wide share found at "/snap/minetest/x1/usr/bin/../share/minetest"
ALSA lib conf.c:4553:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
2024-03-14 09:37:25: ERROR[Main]: Audio: Global Initialization: Failed to open device
2024-03-14 09:37:25: ERROR[Main]: Irrlicht: Error: Need running XServer to start Irrlicht Engine.
2024-03-14 09:37:25: ERROR[Main]: Irrlicht: Could not open display, set DISPLAY variable
2024-03-14 09:37:25: ERROR[Main]: An unhandled exception occurred: "Could not initialize the device with any supported video driver"
2024-03-14 09:37:25: ERROR[Main]: In thread 7fc0c7d983c0:
2024-03-14 09:37:25: ERROR[Main]: /root/parts/minetest/src/src/main.cpp:116: int main(int, char**): A fatal error occurred: "Could not initialize the device with any supported video driver"
Aborted (core dumped)

```

**Comment by jnsgruk** [comment]
Ooops! Fixed! 
image

**Comment by popey** [comment]
Still failing here:

```bash
alan@nuc:~/Source/jnsgruk/minetest$ snap run minetest
2024-03-14 10:39:23: WARNING[Main]: system-wide share not found at "/usr/share/minetest"
2024-03-14 10:39:23: WARNING[Main]: system-wide share found at "/snap/minetest/x2/usr/bin/../share/minetest"
/dev/shm/jack_db-1000/__db.001: No such file or directory
2024-03-14 10:39:23: ERROR[Main]: Irrlicht: Error: Need running XServer to start Irrlicht Engine.
2024-03-14 10:39:23: ERROR[Main]: Irrlicht: Could not open display, set DISPLAY variable
2024-03-14 10:39:23: ERROR[Main]: An unhandled exception occurred: "Could not initialize the device with any supported video driver"
2024-03-14 10:39:23: ERROR[Main]: In thread 7f34a61153c0:
2024-03-14 10:39:23: ERROR[Main]: /root/parts/minetest/src/src/main.cpp:116: int main(int, char**): A fatal error occurred: "Could not initialize the device with any supported video driver"
Aborted (core dumped)

```

**Comment by popey** [comment]
Scratch that, pilot error...

image

**Review by popey — APPROVED** [review]
LGTM!

**Pull request merged**
